### ISSUE TITLE
Invalid tmpdir variable value in BaseTest

### ISSUE THREAD

**Issue by rydnr** [antlr/stringtemplate4#103]
When trying to run the tests (StringTemplate 4.0.8) from Maven, some of them fail since they rely on generating temporary files.

Such files use the "tmpfile" variable in BaseTest, and concatenate a suffix. However, the variable doesn't include a trailing slash, so the tests try to create files such as /tmpdir53368/group.stg, which are not allowed and thus fail with "can't write file" errors.

**Comment by sharwell** [comment]
I've had a problem with this, but for a different reason. On my machine, `tmpdir` always had a trailing file separator so the issue you describe never occurred. The part I was uncomfortable with is the test output was not placed underneath the `target` folder which Maven creates during the build. As a result, the `mvn clean` operation does not remove temporary files/folders created during testing.

The best solution for Maven users would be to change the location of `tmpdir` so it always points to a folder within the build's `target` folder.
