### ISSUE TITLE
Scala Support

### ISSUE THREAD

**Issue by sirinath** [antlr/stringtemplate4#112]
Is it possible to add Scala supported language?

**Comment by sharwell** [comment]
StringTemplate 4 is just a runtime library. When compiling Scala code for the JVM, you should be able to use it directly. However, when compiling Scala to another platform, you would need a port of StringTemplate in order to use it.

> :memo: Ports of StringTemplate 4 to other languages are fully independent libraries which are not maintained as part of this project.

**Comment by bmc** [comment]
Note that there's a Scala wrapper library (which, full disclosure, I wrote) for String Template. See <http://software.clapper.org/scalasti/>
