### ISSUE TITLE
ST.format() Javadoc examples not with expected result 

### ISSUE THREAD

**Issue by chwt** [antlr/stringtemplate4#113]
In the [Java API doc of ```ST.format()```](http://www.stringtemplate.org/api/org/stringtemplate/v4/ST.html#format-java.lang.String-java.lang.Object...-) the following example code statements can be seen:

    ST.format("name, phone | <name>:<phone>", n, p);
    ST.format("<%1>:<%2>", n, p);
    ST.format("<name>:<phone>", "name", x, "phone", y);

But that example statements do not work as expected:

    import org.stringtemplate.v4.ST;

    public class Main {
        public static void main(String[] args) {
            String n = "n";
            String p = "p";
            String x = "x";
            String y = "y";
            System.out.println(ST.format("name, phone | <name>:<phone>", n, p));
            System.out.println(ST.format("<%1>:<%2>", n, p));
            System.out.println(ST.format("<name>:<phone>", "name", x, "phone", y));
        }
    }

results in the following output:

    context [anonymous] 1:15 attribute name isn't defined
    name, phone | :
    n:p
    :
    context [anonymous] 1:22 attribute phone isn't defined
    context [anonymous] 1:1 attribute name isn't defined
    context [anonymous] 1:8 attribute phone isn't defined

How should ```ST.format()``` be used?

**Comment by parrt** [comment]
dang. i saw something similar myself recently. i must have added a regression recently. sorry.

**Comment by sharwell** [comment]
@parrt I can't find any indication that `ST.format` ever supported any form except the one with positional arguments.
