### ISSUE TITLE
Should be able to have dictionary key "default"

### ISSUE THREAD

**Issue by jsnyders** [antlr/stringtemplate4#116]
I think it should be possible to have a dictionary key named "default". The default for the dictionary should not pollute the namespace for keys.
Example:

```
delimiters "$","$"
d1 ::= [
  "default": "A",
  default: "B"
]
main() ::= <<
$d1.default$
$d1.foobar$
>>
```

Expected output

```
A
B
```

Actual

```
B
B
```

I also tried $d1.("default")$ but got the same result.

**Comment by KvanTTT** [comment]
Yes! This problem occures in ANTLR with parser rule named as "default" for C# runtime (tool generate not compilable code).

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/stringtemplate4/commit/8ad2c3dbdceeb33266da748fc209b45218916f08
