### ISSUE TITLE
StringTemplate Doc Link - Raw Format

### ISSUE THREAD

**Issue by quenio** [antlr/stringtemplate4#133]
The Doc link on the StringTemplate web site takes you to the raw markdown content:
https://raw.githubusercontent.com/antlr/stringtemplate4/master/doc/index.md

**Comment by sharwell** [comment]
Sure does!

Thanks for the report :smile: 

If you want to fix them, it appears to affect several links in the following commits:

* antlr/website-st4@6b5b197d5467fda6e1d3821e7c14247ed69a572d
* antlr/website-st4@6805ef50a36cff6b65943e2d9b5e3c65337fb4f9

**Comment by parrt** [comment]
Link is now correct: https://github.com/antlr/stringtemplate4/blob/master/doc/index.md
