### ISSUE TITLE
ST copy-constructor does shallow copy

### ISSUE THREAD

**Issue by Groostav** [antlr/stringtemplate4#142]
The docs dont make the expected behaviour clear, but I'm pretty sure this is in error:

``` kotlin
//see https://github.com/antlr/stringtemplate4/blob/master/doc/null-vs-empty.md
@Test fun `when using String Template copy constructor should be able to re use template object`(){

  //setup
  val sourceTemplate = ST("""Custom<if(codes)> (<codes; separator=", ">)<endif>""");
  var template : ST;

  // test 1
  val codes = listOf(1, 2, 3)
  template = ST(sourceTemplate);
  template.add("codes", codes)
  val result = template.render();
  assertThat(result).isEqualTo("Custom (1, 2, 3)")

  //test 2
  template = ST(sourceTemplate);
  template.add("codes", emptyList<Int>())
  val result2 = template.render();
  assertThat(result2).isEqualTo("Custom ()") //!!!

  //test 3; if I make a new one verbatim...
  template = ST("""Custom<if(codes)> (<codes; separator=", ">)<endif>""");
  template.add("codes", emptyList<Int>())
  val result3 = template.render();
  assertThat(result3).isEqualTo("Custom")

  //this is expected!?
}
```

_note: language is [Kotlin](https://kotlinlang.org/) aka c#ified Java._

note that by adding "codes" in test 1 the `impl` is modified by reference on `sourceTemplate`. When the copy constructor is called `locals` is cleared to an array of nulls, but that seems to be treated differently here. 

Is this correct behavior?

Sorry for wasting your time if it is, it just seems a little odd and, as someone who has recently been burned a couple times by forgetting a `this.whatever = new Whatever(that.whatever)` a couple times recently, it seems like that might be whats going on here.

**Comment by parrt** [comment]
I believe this was fixed by https://github.com/antlr/stringtemplate4/commit/c3999aab4832ec590c36999368a7dd8e9e53c316

**Comment by Groostav** [comment]
it was present in 4.0.8 and is gone in 4.3.4
