### ISSUE TITLE
Can't reference variable in dictionary

### ISSUE THREAD

**Issue by suemi994** [antlr/stringtemplate4#161]
When I'm writing a String Template Group file, I found that reference a variable in dictionary value string won't lead to the variable, but to the raw string. An example in your book  is following.

```
javaToSQLValueMap ::= [
	"Date":"new java.sql.Date(<val>.getTime())",
	default : "<val>"
]
fieldValue(type,val="o")::="<javaToSQLValueMap.(type.simpleName)>"
```

When I use fieldValue , this is the result:

```java
prep.setDate(3+1,new java.sql.Date(<val>.getTime()));
```

If the variable is not visible in this scope, then I will get 

```java
prep.setDate(3+1,new java.sql.Date(.getTime()));
```

But it'not, so I think the cause is your definition of STRING token in lexer.

**Comment by sharwell** [comment]
What happens if you use an anonymous template instead of a string for your dictionary value?

```
javaToSQLValueMap ::= [
	"Date": {new java.sql.Date(<val>.getTime())},
	default : {<val>}
]
fieldValue(type,val="o")::="<javaToSQLValueMap.(type.simpleName)>"
```

**Comment by suemi994** [comment]
Thank you for your help, it works now !
