### ISSUE TITLE
Unterminated comment starting at 1:0: '!>' missing

### ISSUE THREAD

**Issue by jlerbsc** [antlr/stringtemplate4#165]
We have "Unterminated comment starting at 1:0: '!>' missing" error message if we start html document with a doctype declaration like this
     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >

**Comment by sharwell** [comment]
StringTemplate comments have the form `<! commented text !>`. I'm actually not sure what the proper escape sequence is so the `<!` appears in the output... @parrt should know.

**Comment by parrt** [comment]
if you're generating html, `<...>` is the the wrong set of delimiters. Use `$...$` or something.

**Comment by jlerbsc** [comment]
Thanks.
