### ISSUE TITLE
Use '&' as a DelimiterChar ?

### ISSUE THREAD

**Issue by ncharles** [antlr/stringtemplate4#172]
Hello,

First, I'd like to thank you for StringTemplate, this is a very useful libraries for us.
We've been using StringTemplate 3 since 2009, and now we'd like to upgrade to 4.0.8, as it promises major improvement.

In our templates, we use & as a delimiter character; we created specific Lexer and Parser for version 3, and it seems in 4.0 the recommended approach is to use `new ST(mycontent, '&', '&')`

However, I never managed to make this work, as it fails with following error message:

> 1:20: expecting '&', found '<EOF>'
> 1:20: expecting '&', found '<EOF>'
> 1:19: '&' came as a complete surprise to me
> 1:20: expecting '&', found '<EOF>'
> 1:20: expecting '&', found '<EOF>'

when content is `&AGENT_RUN_INTERVAL&`

I tried with '!', which fails in the same way, but using 'ç' succeed.
My guess is that & and ! are reserved for AND and NOT respectively, but this is not documented (and it is not in https://github.com/antlr/stringtemplate4/pull/149 either)

Is there a way to use & as a separator in 4.0 ? If so, what is the prefered way to make it work ?

Kind regards,
Nicolas

**Comment by sharwell** [comment]
💭 Totally just guessing right now, but I wonder if it's messing up because of the `&&` operator. For example, using the default delimiters an expression might be:

```
<AGENT_RUN_INTERVAL&&SOMETHING>
```

**Comment by ncharles** [comment]
Thank you @sharwell - is there a way I can help you to fix it? My knowledge in parsing and lexing is not very good though, but I can at least test proposed solution,

**Comment by ncharles** [comment]
Hi,
Is there any way I can help in the resolution of this issue ?

**Comment by parrt** [comment]
I believe that we have added a warning so that it doesn't just mysteriously not work. https://github.com/antlr/stringtemplate4/pull/149

**Comment by ncharles** [comment]
Unfortunately, this ends all hopes to upgrade from ST3 to ST4 as all of our template are using &, and our user-defined template also use & as separator. There is no upgrade path possible without support for this value (automatic rewrite of template is most likely to fail because we use it to generate plenty of scripts)

Anyway, thank you for fixing the warning, and thank you for developping StringTemplate, which is super useful
