### ISSUE TITLE
What work is needed to upgrade st4 to use antlr4?

### ISSUE THREAD

**Issue by xied75** [antlr/stringtemplate4#175]
Currently st4 needs antlr3 runtime. I wonder how much work is required to upgrade this dependency to antlr runtime v4?

**Comment by KvanTTT** [comment]
antlr4 also use antlr3 :)

**Comment by xied75** [comment]
@KvanTTT Thanks for the head up. :) I think it definitely worth it to break this chain.

A quick question if you don't mind answering, I see there is a
```public partial class CodeGenerator : Antlr.Runtime.Tree.TreeParser``` with a CodeGenerator.g3, what is this? (Sorry that I started with Antlr4, has zero knowledge about the history). Is this concept still around in Antlr4?

**Comment by xied75** [comment]
Dear all, just to say I've got a working st4 on antlr4.standard, if you think it's any value to the community, I could turn that into a public repository. Let me know.

**Comment by parrt** [comment]
Wow! That sounds like a lot of work. How big were the changes?  Oh and I guess that's for C# not Java.

**Comment by parrt** [comment]
Well, it's no longer my focus so I'm unlikely to find the time to update. thanks though!
