### ISSUE TITLE
Template imports ignore UTF-8 setting

### ISSUE THREAD

**Issue by kkress2000** [antlr/stringtemplate4#205]
Test: 

	@Test public void testImportUtfTemplateFileSameDir() throws Exception {
		/*
		dir
			group1.stg		(that imports c.st)
			c.st
		 */
		String dir = getRandomDir();
		String groupFile =
			"import \"c.st\"\n" +
			"a() ::= \"g1 a\"\n"+
			"b() ::= \"<c()>\"\n";
		writeFile(dir, "group1.stg", groupFile);
		writeFile(dir, "c.st", "c() ::= \"2∏r\"\n");

		STGroup group1 = new STGroupFile(dir+"/group1.stg");
		ST st = group1.getInstanceOf("c"); // should see c()
		String expected = "2∏r";
		String result = st.render();
		assertEquals(expected, result);
	}
<failure type="org.junit.ComparisonFailure" message="expected:<2[∏]r> but was:<2[?]r>">

**Comment by parrt** [comment]
This is working for me, @kkress2000:

```
@Test public void testImportUtfTemplateFileSameDir() throws Exception {
		/*
		dir
			group.stg		(that imports c.st)
			c.st
		 */
		String dir = getRandomDir();
		String groupFile =
			"import \"c.st\"\n" +
			"a() ::= \"g1 a\"\n"+
			"b() ::= \"<c()>\"\n";
		writeFile(dir, "group.stg", groupFile);
		writeFile(dir, "c.st", "c() ::= \"2∏r\"\n");

		STGroup group1 = new STGroupFile(dir+"/group.stg");
		ST st = group1.getInstanceOf("c"); // should see c()
		String expected = "2∏r";
		String result = st.render();
		assertEquals(expected, result);
	}
```
