### ISSUE TITLE
Tests failed while building in headless environment

### ISSUE THREAD

**Issue by smartnet-club** [antlr/stringtemplate4#211]
testEarlyEval2(org.stringtemplate.v4.test.TestEarlyEvaluation)  Time elapsed: 0.006 sec  <<< ERROR!
java.awt.HeadlessException

Similar problem described here: https://stackoverflow.com/questions/47575673/headless-exception-while-gui-testing-java-swing-with-gitlab-ci

Is it possible to switch off tests for windows environment?

**Comment by parrt** [comment]
Hmm...not sure how to hide those w/o cutting out.

**Comment by sharwell** [comment]
@smartnet-club You can exclude the test class by passing the following argument to Maven:

```
-Dtest=\!TestEarlyEvaluation*
```

🔗 From https://stackoverflow.com/a/37794230

**Comment by smartnet-club** [comment]
It works!
Thanks!
