### ISSUE TITLE
ST4 ObjectModelAdaptor unable to find Boolean kotlin property starting with "is"

### ISSUE THREAD

**Issue by hwasin** [antlr/stringtemplate4#219]
Affected ST4 version: 4.0.2

Lets create simple 
```
class PojoKotlin(var isTrue: Boolean = true) 
```
object with isTrue set to "true"

If i want to render following template:

```
render_pojo(pojo) ::= <<
<if(pojo.isTrue)>
property is true
<else>
property is false
<endif>
>>
```
then "property is false" is rendered.

This happens because ObjectModelAdaptor unable to find isTrue property when kotlinc compiler is used to fullfill reflection data. If property starts with "is" then "isTrue()" getter is generated but ST4 expects either "getIsTrue" or "isIsTrue". If you remove "is" prefix or use Java class then ST4 handles it perfectly. 

Please check my debug screenshot: 

![kotlin-bug](https://user-images.githubusercontent.com/6069289/64192225-d79d6e80-ce82-11e9-91b9-fb88cda5b1a1.jpg)

**Comment by parrt** [comment]
Oh that's a drag. Not sure I should change this so it works with Kotlin. won't that break the Java connection?

**Comment by hwasin** [comment]
You can add extra if statement which checks whether methodSuffix starts with "is" if so then try to look it up. This should not break compatibility with Java.

> Not sure I should change this so it works with 

Not a big problem, just FYI. You are may close the issue

**Comment by parrt** [comment]
ok, thanks.
