### ISSUE TITLE
ST4.2 has a maven dependancy on 3.5.2 antlr runtime

### ISSUE THREAD

**Issue by totierne** [antlr/stringtemplate4#226]
Is 3.5.2 antlr runtime required in the use of ST4.2 - or can a newer antlr runtime (4.x) be used?

**Comment by totierne** [comment]
Quick Start
    Samples

Quick Start
OS X

$ cd /usr/local/lib
$ sudo curl -O http://www.stringtemplate.org/download/ST-4.2.jar
$ export CLASSPATH=".:/usr/local/lib/ST-4.2.jar:$CLASSPATH"

suggests the runtime is not required to use the ST4.2 jar i.e. it is complie time not run time.

**Comment by sharwell** [comment]
StringTemplate uses ANTLR 3 internally, not ANTLR 4

**Comment by parrt** [comment]
@totierne yep, definitely needs ANTLR to run.  Does this answer your question? can I close?

**Comment by totierne** [comment]
Thanks, from the dependancy management point of view 3.5.2 runtime seems a bit old. Can close.
