### ISSUE TITLE
Consistent Code Formatting

### ISSUE THREAD

**Issue by Clashsoft** [antlr/stringtemplate4#227]
This is neither a feature request nor a bug report, but more like a call for action to improve code quality and maintainability. The current codebase is very inconsistent with its use of tabs vs spaces, sometimes arbitrarily mixing the two within the same line (which is ok when using tabs for indentation and spaces for alignment, but not randomly). Viewing the files with an editor that has tab width set to 4 is ok, but e.g. on GitHub it becomes messy because it has 8-space tabs by default.

IntelliJ:

![Screenshot 2019-12-22 at 12 22 54](https://user-images.githubusercontent.com/4145923/71321135-c9b53d00-24b5-11ea-8ee8-1778a27b2cdf.png)

GitHub:

![Screenshot 2019-12-22 at 12 25 41](https://user-images.githubusercontent.com/4145923/71321169-2dd80100-24b6-11ea-8fe0-a83a04745682.png)

I believe adding an `.editorconfig` and perhaps adding a style guide for contributors is a good first step. I'd be willing to make a PR. I am not sure about how to handle the existing code, as autoformatting it would produce a very large changeset that is hard to merge and generally frowned upon.

Re. the choice of tabs vs. spaces in this project, I ran the following commands, indicating that tabs are currently more widely used:

```zsh
$ find src -name '*.java' -print0 | xargs -0 grep -o '    ' -- | wc -l 
    3695
$ find src -name '*.java' -print0 | xargs -0 grep -o $'\t' -- | wc -l
   12207
```

**Comment by parrt** [comment]
Yeah, a quick `expand -4` on the codebase is a good idea.

**Comment by Clashsoft** [comment]
Closing now that #230 is merged.
