### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by Clashsoft** [antlr/stringtemplate4#229]
The tests as of revision 8bfc30a703537c50d654077bda6a1dd8fa4f696b seem to be somewhat brittle when using different test runners and JDK versions. Here are some observations.

To avoid problems like this in the future, it would be very useful to set up Travis CI or GitHub actions.

`mvn test`:

```
Results :

Failed tests:   testImportUtfTemplateFileSameDir(org.stringtemplate.v4.test.TestImports): expected:<2[?]r> but was:<2[?]r>

Tests run: 629, Failures: 1, Errors: 0, Skipped: 2
```

This seems to be an encoding problem.

Here is the output of `mvn --version`:

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3/libexec
Java version: 1.8.0_222, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.2", arch: "x86_64", family: "mac"
```

**Comment by parrt** [comment]
Yikes, yeah, I haven't run the tests since probably Java 9!

**Comment by Clashsoft** [comment]
The IntelliJ test runs must have been misconfigured, now it fails the same test as `mvn test`. I'm currently investigating.
