### ISSUE TITLE
JavaScript port?

### ISSUE THREAD

**Issue by tdjastrzebski** [antlr/stringtemplate4#251]
This really is not an issue but I was wondering if anyone thought of or worked on JavaScript port.
I am not aware of any decent string template engine for JavaScript. I think stringtemplate could fill in this gap.
Update: I found JavaScript port was attempted by @jsnyders but it looks like the the project is abandoned. [link](https://github.com/jsnyders/StringTemplate-js)

**Comment by bmix** [comment]
On the frontpage this is referenced: https://github.com/jsnyders/StringTemplate-js

**Comment by mike-lischke** [comment]
Not sure if it still matters to you, but I ported it to TypeScript: https://github.com/mike-lischke/stringtemplate4ts, from you can easily create a JS port.
