### ISSUE TITLE
StringRenderer xml-encode leads to invalid XML

### ISSUE THREAD

**Issue by tkalmar** [antlr/stringtemplate4#260]
StringRenderer `xml-encode` leads to invalid xml

for example the String `🩳`  leads to the XML-Entity: `&#55358;&#56947;` which is according to XML-Spec (https://www.w3.org/TR/REC-xml/#NT-Char) not in the range of allowed chars for XML (Note the ranges differ between XML 1.0 and XML 1.1)
This should either be: 
* fixed (don't know what would be the right way?) perhaps raising an error or rejecting the input? Filtering offending chars would also be an option
* documented

Im not shure if for an UTF-8 encoded XML document the encoding of `<`, `>`,`"` and `'` would be sufficent and all other characters should be passed through

**Comment by parrt** [comment]
Looks like it might be not hex-encoding the values.

**Comment by tkalmar** [comment]
No it is hex encoding the value, but the `🩳` is in its encoded form (&#55358;&#56947;) not valid for XML (see the linked spec)

**Comment by Clashsoft** [comment]
The emoji is encoded in the Java String as two `char`s due to the code point being over the two byte limit, hence the strange encoded form. It's called a surrogate pair. The fix would be to loop over the code points instead of the characters of the string. I'll make a PR in a bit.
