### ISSUE TITLE
Has anyone ported the antlr3 grammar files in the compiler package to antlr4?

### ISSUE THREAD

**Issue by jarrodhroberson** [antlr/stringtemplate4#266]
I am wanting write a port of StringTemplate in Go 1.15 and would like to be able to use the STParser/Group/CodeGenerator grammar files if possible. 

Has anyone ported those grammar files to something that antlr4 can deal with?

**Comment by parrt** [comment]
I'm not aware of a port to Go. sorry.   Certainly the grammar part would translate over but whatever actions are in there would not.
