### ISSUE TITLE
StringTemplate eats up double backslashes

### ISSUE THREAD

**Issue by StephanRichter** [antlr/stringtemplate4#271]
I'm not quite sure whether this is a bug or a desired behaviour...

How to reproduce:

```java
import org.stringtemplate.v4.ST;

public class STTest {
	public static void main(String[] args) {
		char backslash = '\\';
		System.out.println(new ST("Why does "+backslash+backslash+" get converted to "+backslash+" ?").render());
	}
}
```
Expected output:
```text
Why does \\ get converted to \ ?
```

Actual output:
```text
Why does \ get converted to \ ?
```

It this is desired behaviour, is there any way to suppress it?

best wishes

**Comment by parrt** [comment]
Hi. Because `\` is special, we need a way to specify just a plain backslash. If there's no valid character after the `\` though it does not try to translate it so I guess they're the same thing. sorry for the confusion!
