### ISSUE TITLE
Add a <replace(attr, regx, str)> function.

### ISSUE THREAD

**Issue by xiemeilong** [antlr/stringtemplate4#274]

**Comment by Clashsoft** [comment]
Can you provide some examples where this would be useful?

**Comment by parrt** [comment]
Hi.  also it violates the rule that we should separate the program from the template and doing such replacements makes the template part of the program.

**Comment by xiemeilong** [comment]
@parrt I want to use it when I need replace some special characters that maybe exist in user input , such as sql or others. And the program  not know which param sholud be preprocessed.  This is maybe the responsibility of template.

**Comment by parrt** [comment]
I suggest you look at the formatter objects. there is a way to specify `format=` or something like that. you can abuse that anyway you want :)
