### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by jetmore** [antlr/stringtemplate4#280]
Sorry for opening a git bug about this, but I wanted to report it somewhere.

https://www.stringtemplate.org/scripts/bottomnav.js has an issue such that not all links are getting rendered.  Contents:

```
document.write("<ul>");
document.write("<li><a href='index.html'>Home</a></li>");
document.write("<li><a href='download.html'>Download</a></li>\n");
document.write("<li><a href='https://github.com/antlr/stringtemplate4/blob/master/doc/index.md>Doc</a></li>\n");
document.write("<li><a href='about.html'>About StringTemplate</a></li>\n");
document.write("<li><a href='support.html'>Support</a></li>  \n");
document.write("<li><a href='https://github.com/antlr/stringtemplate4/issues'>Bugs</a></li> \n");
document.write("</ul>\n");
document.write("<small>&copy; Copyright StringTemplate / Terence Parr 2013</small>");
```

The Doc link is missing a trailing single-quote.  This makes the Doc link not show up in the footer, and breaks the About StringTemplate link.  Not the end of the world, just thought I'd report it since I noticed it.  Thanks

**Comment by parrt** [comment]
Just pushed a fix. Thank you very much. it will take a bit to propagate on the actual website.
