### ISSUE TITLE
Add escaping for ' and " in the StringRenderer "xml-encode"

### ISSUE THREAD

**Issue by feanor777** [antlr/stringtemplate4#283]
Is it possible to add encoding for the ' and " inside the StringRenderer class?

It's recommended to always escape these characters, to avoid issues, for example when you're setting value inside of attribute.
https://stackoverflow.com/questions/7381974/which-characters-need-to-be-escaped-in-html

Thank you!

**Comment by parrt** [comment]
Ah.  Since I'm more in maintenance mode, can you subclass the renderer and make the changes you want? Then you can register the new kind of object.

**Comment by feanor777** [comment]
Thank you for the answer!
Yes, I know, it's possible to use your own Renderer class, just was thinking that it would be good to add these things to the StringRenderer class.
