### ISSUE TITLE
CDATA section

### ISSUE THREAD

**Issue by greuelpirat** [antlr/stringtemplate4#291]
I set `$` for HTML delimiters. But how can I escape `<!` for comments? I need to write a CDATA section `<![CDATA[....]]>`.

But what ever I try, it always gets escaped by string template: `<!--[CDATA ....`

```
logException(exception) ::= <<
<div class="log-exception">
  <div class="message">$exception.message$</div>
  <div class="details">$exception.type$</div>
  <div class="details"><![CDATA[$exception.stackTrace$]]></div>
  <div class="inner-exception">
  $exception.innerException:logException()$
  </div>
</div>
>>
```

is there really no way?

**Comment by parrt** [comment]
Yikes. haven't looked at this lib for years. Please try `\<` to escape the first angle bracket maybe?

**Comment by greuelpirat** [comment]
Uff, I just realized, that the CDATA-section is written correctly. For some reason I do not understand it are all browsers (tested with chrome, edge and firefox) that escapes the CDATA section.

sorry and thanks! I close this issue
