### ISSUE TITLE
Loading template group from STGroupDir in app running on Tomcat 8 fails

### ISSUE THREAD

**Issue by Mooninaut** [antlr/stringtemplate4#293]
StringTemplate version: 4.3.1

I'm migrating a web application from Tomcat 7 to Tomcat 8. It appears something in the class loader behavior has changed between the versions.

My app calls `STGroupDir group = new STGroupDir("com/example/app/path/to/templates");`

When running on Tomcat 7, after the line `root = cl.getResource(dirName);` at `STGroupDir.java:72` the variable `root` has the value

`jar:file:/path/to/exploded/app/WEB-INF/lib/my-component.jar!/com/example/app/path/to/templates`

Running on Tomcat 8, `root` has the value

`jar:file:/path/to/exploded/app/WEB-INF/lib/my-component.jar!/com/example/app/path/to/templates/`

My app then calls `ST st = group.getInstanceOf("/TemplateGroup/someTemplate");` to load `someTemplate` from `...path/to/templates/TemplateGroup.stg`.

When `load()` calculates `groupFileURL` on line `STGroupDir.java:128`, the value is

`jar:file:/path/to/exploded/app/WEB-INF/lib/my-component.jar!/com/example/app/path/to/templates//TemplateName.stg`

The double slash prevents it from successfully loading the template group file, and `getInstanceOf()` returns `null`.

**Comment by parrt** [comment]
oh wow. Sorry about that. I'm probably not joining paths correctly. I'm currently focused on 1 billion other things but I would welcome a PR if you have time.

**Comment by parrt** [comment]
line 128 in STGroupDir is the issue:

```
groupFileURL = new URI(root+parent+GROUP_FILE_EXTENSION).normalize().toURL();
```

 which looks to be what you are fixing in your PR.   I wonder if we can just use a proper URL or file path "join" to avoid the extra code with the special tests that you've created.

**Comment by Mooninaut** [comment]
There is no simple URL/URI path join API in Java 1.6. The first line of lookupTemplate adds a leading `/` to the path, so `root.resolve(parent + GROUP_FILE_EXTENSION)` will treat `parent` as an absolute path, and strip the path from `root`.  Now, `load()` could remove that leading `/` and call `resolve()`, but at that point why bother? The URL/URI resolving code is very, very complex.

I've updated the PR to be more general, moving the logic to `Misc.joinPathSegments()` and testing that.

**Comment by parrt** [comment]
I would imagine we can move to Java 7 or 8 at this point. Is there something we can rely on in the new versions of Java?

**Comment by Mooninaut** [comment]
I tried a Java 7 implementation using NIO at https://github.com/Mooninaut/stringtemplate4/tree/java1.7 , but it causes several dozen tests to fail on Windows. I don't know that it's worth it.

**Comment by parrt** [comment]
I didn't see any changes in that fork of yours but have you seen this that was linked to from the documentation? 

https://maven.apache.org/plugin-developers/common-bugs.html#Converting_between_URLs_and_Filesystem_Paths

 I'm going to look in there as well

**Comment by parrt** [comment]
What if we simply removed '//' from any URL string? @Mooninaut

**Comment by parrt** [comment]
I just pushed a new snapshot of 4.3.2 via maven.  can you give it a try?

**Comment by Mooninaut** [comment]
Works great!

**Comment by parrt** [comment]
hooray!
