### ISSUE TITLE
How to pass arguments for indirect template call?

### ISSUE THREAD

**Issue by Skoti** [antlr/stringtemplate4#296]
I have a template:
```
someTemplate(arg1,arg2) ::= <<
<arg1> - <arg2>
>>
```
which I can call indirectly like this:
```
indirect(templateName) ::= <<
<(templateName)("1", {2})>
>>
```
where I pass: `.add("templateName", "someTemplate")`
and the output is: `1 - 2`

But I'd like to pass arguments as well like this:
```
indirectWithArgs(templateName, templateArgs) ::= <<
<(templateName)(templateArgs)>
>>
```
where I pass: `.add("templateArgs", "\"1\",{2}")`
but the output is: `"1",{2} - `

How can I pass the arguments for the indirect template?

I've tried:
- `.add("templateArgs", listOf(1, 2)` that gives `12 - `
- `.add("templateArgs", listOf(listOf(1, 2)))` that gives `12 - `
-  `.add("templateArgs", listOf(listOf(1), listOf(2)))` that gives `12 - `
- `.add("templateArgs", listOf("\"1\"", "{2}"))` that gives `"1"{2} - `
- `.add("templateArgs", listOf(listOf("\"1\"", "{2}")))` that gives `"1"{2} - `
- `.add("templateArgs", listOf(listOf("\"1\""), listOf("{2}")))` that gives `"1"{2} - `

Seems no matter how I pass the args it treats them as one argument.

I see a possible workaround would be to use as many arguments in `indirectWithArgs` as we want to pass into the `someTemplate` but that's a terrible solution if you have more indirect template calls or if you're using `addAggr` to create an aggregate.

**Comment by parrt** [comment]
Hmm...I don't think I though of this use case. We'd need python's `*args` kind of thing.

**Comment by Skoti** [comment]
Is this closed and will never be added?

**Comment by parrt** [comment]
Yeah,I just don't think it's that common of a need and given all of the other projects I have it's a low priority I'm sorry to say!
