### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by Skoti** [antlr/stringtemplate4#297]
assume a template like:
```
template() ::= <<
startText
    nestText
>>
```

then when calling this in a template like:
```
test() ::= <<
^template()^

    ^template()^

        ^template()^

exampleA ^template()^

    exampleB ^template()^

        exampleC ^template()^
>>
```

the output is:
```
startText
    nestText

    startText
        nestText

        startText
            nestText

exampleA startText
    nestText

    exampleB startText
    nestText

        exampleC startText
    nestText
```
So in the first 3 (unnamed examples) it works correctly in all cases. But as soon as you add some text before the template, it breaks the indentation.
For `exampleA` it's correct because there is no previous indentation.
But for `exampleB` and `exampleC` it's incorrect as it always puts the `nestText` indented with 4 spaces from the beginning of the next line instead of increasing the indentation by 4 spaces from the previous line.

It should be:
```
exampleA startText
    nestText

    exampleB startText
        nestText

        exampleC startText
            nestText
```

**Comment by parrt** [comment]
Hi. It's been awhile but I think that's what I baked in: only pure indentation whitespace is considered.

**Comment by Skoti** [comment]
Oh what a pity 😢  Would it be complicated to add an option to also correctly indent such cases?

**Comment by parrt** [comment]
Hi. Well,The problem is I have so many open source projects to maintain and I have to set priorities. I've also just started a new job so it's hard. I would consider a PR if there is a simple implementation and set of semantics we could describe...

**Comment by Skoti** [comment]
Better late than never 😄 

The fix is to enclose the whole thing in an anonymous template and by default it will [anchor](https://github.com/antlr/stringtemplate4/blob/master/doc/expr-options.md) new lines to the beginning of the expression!
So `^{exampleB ^template()^}^` instead of `exampleB ^template()^`  correctly produces:
```
    exampleB startText
        nestText
```
