### ISSUE TITLE
Integrating stringtemplate4 into OSS-Fuzz

### ISSUE THREAD

**Issue by vargen** [antlr/stringtemplate4#298]
Hi all,

I have prepared the integration [CodeIntelligenceTesting/oss-fuzz@4c510b8](https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/4c510b8887a3bc6b9f3b0c2a222b15a644a02dbc) of stringtemplate4 into google oss-fuzz. This will enable continuous fuzzing of this project, which will be conducted by Google. Bugs that will be found by fuzzing will be reported to you.

The integration requires a primary contact, someone to deal with the bug reports submitted by oss-fuzz. The email address needs to belong to an established project committer and be associated with a Google account as per [here](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/). This will provide you with access to ClusterFuzz, crash reports, and fuzzer statistics. More than 1 person can be included. Please let me know who I should include, if anyone.

Ideally, the fuzz tests would live in this repo (stringtemplate4) instead of the oss-fuzz repo to better stay in sync with the code. We can create a PR to do that if you are interested.

[Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) is used for fuzzing Java applications. Jazzer is a coverage-guided, in-process fuzzer for the JVM platform developed by Code Intelligence. It is based on libFuzzer and brings many of its instrumentation-powered mutation features to the JVM.
Jazzer has already found a lot of critical bugs in JVM applications.

Please let me know if you have any questions regarding fuzzing or the oss-fuzz integration.

**Comment by parrt** [comment]
Hi. Sounds like the useful project but at this time I prefer not to add this. thank you.
