### ISSUE TITLE
ST4-testjar not found 

### ISSUE THREAD

**Issue by mamtananavati** [antlr/stringtemplate4#300]
When including ST4 V 4.3.2 in project pom it isnt pulling in ST4-testjar 
Running `mvn dependency:tree` throws the below warning message

`[WARNING] The POM for org.antlr:ST4:jar:4.3.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details`

**Comment by parrt** [comment]
hmm...it's part of the testing stuff. I wonder if this can just be excluded from deployments? I couldn't figure out another way to get a test.jar into the mvn ecosystem.

**Comment by pzygielo** [comment]
> transitive dependencies (if any) will not be available

Above of course makes 4.3.2 hardly usable without explicitly defining dependencies. I'd rather avoid that.

**Comment by parrt** [comment]
Would love to fix!  Could you tell me how to fix the poms? I literally don't understand maven. I can release today.

**Comment by parrt** [comment]
I think this is better:

https://github.com/antlr/stringtemplate4/blob/master/pom.xml

**Comment by parrt** [comment]
I deployed 4.3.3-SNAPSHOT.  Can you use that and see if it works? thanks!

**Comment by mamtananavati** [comment]
Thank you , will give it a try.

**Comment by pzygielo** [comment]
> I think this is better:
> 
> https://github.com/antlr/stringtemplate4/blob/master/pom.xml

I think I have slightly better solution even then that. But I will need few more minutes to fork and prepare PR.

**Comment by parrt** [comment]
I have released 4.3.3 :)

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/stringtemplate4/pull/301
