### ISSUE TITLE
Should support coercing the (non)emptiness of a Map or Collection to a Boolean for conditionals of the form `<if(a.p)>` where `p` is a Collection or Map

### ISSUE THREAD

**Issue by twwwt** [antlr/stringtemplate4#307]
According to [this comment](https://github.com/antlr/stringtemplate4/issues/92#issuecomment-66946523) String template coerces a conditional statement `<if(x)>` where `x` is an empty `Map` or `Collection` attribute to the Boolean value `false`; and `true` if `x` is non-empty. This doesn't seem to work analogously for a statement `<if(a.p)>` where `a` is an attribute and `p` is a `Map` or `Collection` property; at least it didn't work for me in a local test. It would be nice if Stringtemplate would support this; I had to introduce an additional Boolean attribute whose value was set from `myList.isEmpty()`.

**Comment by twwwt** [comment]
Might be related to #169.

**Comment by parrt** [comment]
hi. yep, looks like same bug. i'll label this as a dup. sorry for hassle.
