### ISSUE TITLE
Thread safety issue

### ISSUE THREAD

**Issue by seojiwon** [antlr/stringtemplate4#61]
We use StringTemplate in multi-threaded configuration, where we create a single `STGroup` instance, and multiple threads call `group.getInstanceOf` and `render`.

The problem is we (sometimes) get `attribute XYZ isn't defined` error, although the attribute `XYZ` (which is a map/dictionary template) is clearly defined in an imported template.

My guess is that StringTemplate has thread safety issues when (but not limited to) a dictionary that is defined in an imported template file is accessed.

I went over the source code and found a few places that potentially have thread safety issue.
1. Lazy initialization of `STGroup` (`STGroupFile`) object. `STGroupFile` calls `load()` method lazily when necessary, so multiple thread can simultaneously initialize the object (which may or may not be a problem). I think probably `load()` should be synchronized.
2. `CompiledST` object is being modified after added to the synchronized `templates` dictionary. 
   For example, in `STGroup.java` in `defineRegion` method `code.defineArgDefaultValueTemplates(this)` and `code.defineImplicitlyDefinedTemplates(this)` is called after the invocation of the `rawDefineTemplate` method, which puts `CompiledST` object into the synchronized map. Thus another thread may see an incomplete `CompiledST` object.

I did not check all the code, so there might be other places with thread safety issues. I made `STGroup.getInstanceOf`, `STGroup.getEmbeddedInstanceOf`, and `ST.render` to be synchronized with respect to the `STGroup` instance, and the attribute error went away.
I suggest that those three methods to be synchronized; but also someone should go over all the code and check if any other thread-safety issue is there. Any code that does lazy evaluation should be examined for thread safety.

**Comment by hartmut27** [comment]
Just as a side node - you need an threadsafe singleton mechanism, to prevent multithreading issues while initializing the STGroup. I've chosen Google Guava's micro caching ```Suppliers.memoize```.
By the way - I did not encounter problems afterwards sharing the intitiatlized STGroup beteween threads.
```
Supplier<STGroup> stGroupSupplier = Suppliers.memoize(
  new Supplier<STGroup>() {
    @Override
    public STGroup get() {
      try {
        return new STGroup(...)
      }
   }
}
```
then
```
stGroupSupplier.get()
```
from the Guava javadoc: "The returned supplier is thread-safe. The delegate's get() method will be invoked at most once."

**Comment by huangyg11** [comment]
@hartmut27 The problem here is the lazy loading of the template file, not the initializing of STGroup. So your code may need to include the loading of template file to work.
