### ISSUE TITLE
String delimiters

### ISSUE THREAD

**Issue by SurealCereal** [antlr/stringtemplate4#90]
I am using StringTemplate in Java source files.  Having `/*<` and `>*/` as delimiters would be extremely useful instead of having to rely on single character delimiters.  Often something unique is required as a delimiter, and two unique characters are hard to come by.

Allowing for _multiple_ opening and closing delimiters would be even more useful; that way a `/*<` & `>*/` sequence would work, as well as a simple `<` & `>` in a sub-template.

**Comment by Clashsoft** [comment]
This may be very hard to implement without breaking API compatibility due to `STGroup.delimiterStartChar` and `.delimiterStopChar` being `public` fields.
