### ISSUE TITLE
Leading CR/LF is lost after Render()

### ISSUE THREAD

**Issue by frederik256** [antlr/stringtemplate4#93]
A string starting with a newline will lose the newline in the rendered template.

Repro:

```
string text = Environment.NewLine + "something invariant";
Template template = new Template(text, '«', '»');            
if (!text.Equals(template.Render())) throw new Exception("Text not invariant.");

```

This is using "Antlr4.StringTemplate" C# package from nuget, version=4.0.6.9004 (running on Windows)

**Comment by sharwell** [comment]
:memo: This does appear to be a bug. The elimination of the first/last newline should only apply to templates defined in a **.stg** file.
