### ISSUE TITLE
Using an attribute with a hypen, followed by a alphanum character throws Antlr4.StringTemplate.Compiler.TemplateException

### ISSUE THREAD

**Issue by frederik256** [antlr/stringtemplate4#94]
The following throws  Antlr4.StringTemplate.Compiler.TemplateException

```
new Template("{A-1}.Something", '{', '}');
```

The following does not:

```
new Template("{A-}.Something", '{', '}');
```

Ideally I'd like to use GUIDs, including those starting with numbers as an attribute but that may need a language spec change.

This is using "Antlr4.StringTemplate" C# package from nuget, version=4.0.6.9004 (running on Windows)

**Comment by parrt** [comment]
Hi. `{A-1}` isn't a valid template expression is it? If you just want text then just use the string "A-1".

**Comment by sharwell** [comment]
@parrt The [`ID` rule in **Group.g**](https://github.com/antlr/stringtemplate4/blob/ca0be2ec227005233a15b19d1c22aef6853a2321/src/org/stringtemplate/v4/compiler/Group.g#L329) supports hyphens, but the [`mID()` method in **STLexer.java**](https://github.com/antlr/stringtemplate4/blob/ca0be2ec227005233a15b19d1c22aef6853a2321/src/org/stringtemplate/v4/compiler/STLexer.java#L448-L464) does not match the same syntax. This means it is possible to declare a template parameter which cannot be referenced by name within an expression.

**Comment by parrt** [comment]
ah! right. sounds familiar. thanks, Sam.
