### ISSUE TITLE
clone ST and add attributes cause an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by herau** [antlr/stringtemplate4#98]
Hello,

i'm using ST4 (4.0.8) and if i want to clone a ST two times; the second clone, `st3`, may cause an `ArrayIndexOutOfBoundsException` when i call the method `add()` on it. 

``` Java
        ST st1 = new ST("$key$");
        st1.add("toto", "tata");
        ST st2 = new ST(st1);
        st2.add("key", "value2");
        ST st3 = new ST(st1);
        st3.add("key", "value3");
```

Exception : 

```
java.lang.ArrayIndexOutOfBoundsException: 1
    at org.stringtemplate.v4.ST.add(ST.java:246)
        at com.###(###.java:85)
```

The clone operation doesn't allow add operations ?

**Comment by jrutten** [comment]
I have seen something similar with the getAttributes and getAttribute(String) methods. The assumption in the code is that locals array contains an entry for every index found in impl.formalArguments. Our scenario is more using groups, but it is essentially encountering this (invalid?) locals assumption. Seems like the retrieval from the locals array should add the entry if not found, defaulting it to EMPTY_ATTR if the array needs to be enlarged to encompass the index.

**Comment by parrt** [comment]
that definitely doesn't sound right. clone must be working improperly.

**Comment by msmyers** [comment]
+1 

```
java.lang.ArrayIndexOutOfBoundsException: 1
	org.stringtemplate.v4.ST.add(ST.java:210)
	com.topspectrum.template.StringTemplateUtil.apply(StringTemplateUtil.java:73)
	com.topspectrum.template.StringTemplateUtil.apply(StringTemplateUtil.java:54)
	com.topspectrum.template.StringTemplateUtil.render(StringTemplateUtil.java:87)
	com.topspectrum.template.SimpleStringTemplate.apply(SimpleStringTemplate.java:37)
	com.topspectrum.template.TemplateUtil.apply(TemplateUtil.java:56)
	com.topspectrum.template.TemplateUtil.apply(TemplateUtil.java:60)
```

```
private static final STGroup DEFAULT_GROUP = new STGroup('$', '$');


    @NotNull
    public static ST instantiate(@NotNull final CompiledST st) {
        return DEFAULT_GROUP.createStringTemplate(st);
    }

    @NotNull
    public static CompiledST compile(@NotNull final String template) {
        CompiledST compile = DEFAULT_GROUP.compile(null, null, null, template, null);

        {
            compile.hasFormalArgs = false;
        }

        return compile;
    }


    @NotNull
    public static ST apply(@NotNull final ST st, @Nullable final Map<String, Object> parameters) {
        Preconditions.checkNotNull(st, "StringTemplate cannot be null!");

        if (null != parameters) {
            for (String key : parameters.keySet()) {
                if (null == key) {
                    continue;
                }

                Object o = parameters.get(key);

                if (null == o) {
                    continue;
                }

                st.add(key, o);
            }
        }

        return st;
    }


    @NotNull
    public static ST compile(@NotNull final String template, @Nullable final Map<String, Object> parameters) {
        return apply(compile(template), parameters);
    }

    @Nullable
    public static String render(@NotNull final String template, @Nullable final Map<String, Object> parameters) {
        return apply(compile(template), parameters).render();
    }

    @Nullable
    public static String render(@NotNull final CompiledST instance, @Nullable final Map<String, Object> parameters) {
        return apply(instance, parameters).render();
    }
```

**Comment by parrt** [comment]
Thanks guys. I hope to get some more bug fixes done during the winter season.

**Comment by msmyers** [comment]
I'm launching a new startup next week. If I have time to track this down I'll send a PR for you. I worked around it by avoid precompiling of templates (which I _assume_ means I'm running _a little_ slower).

**Comment by kilidarria** [comment]
See my comment on Bug in ST.java line 245 #72 it may point to the same problem here  st.add in 4.0.8 is if ( name==null ) {  I was crashing on 	Object curvalue = locals[arg.index]; line 249

**Comment by vc13819** [comment]
Is there a version of StringTemplate that has this bug fixed. The latest version is still 4.0.8 on mavenrepository.

I am seeing the same error when using stGroupDir.getInstanceOf(...) call.
Is there a workaround?

**Comment by vc13819** [comment]
FWIW...it was STRawGroupDir that was causing problem. Moving to StGroupDir seems to have helped (Note of caution, this needs modification to templates to include formal parameters)

**Comment by parrt** [comment]
Thanks for the further report.

**Comment by parrt** [comment]
Added a unit test and fixed properly I think.
